# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgres
  database: eecs_development
  port: 5432

test:
  adapter: postgres
  database: eecs_development
  port: 5432

production:
  adapter: postgres
  database: eecs_development
  port: 5432
